services:
  backend:
    build:
      context: ./backend
    container_name: sentinelai-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: sentinelai-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"