"""expand mission model

Revision ID: 145e259673a3
Revises: 6feb3392d152
Create Date: 2026-07-15 21:59:40.545955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '145e259673a3'
down_revision: Union[str, Sequence[str], None] = '6feb3392d152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('environment', sa.String(length=100), nullable=True))
    op.add_column('missions', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('missions', sa.Column('risk_tolerance', sa.String(length=50), nullable=True))
    op.add_column('missions', sa.Column('personnel', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('vehicles', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('equipment', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('budget', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('constraints', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('missions', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('missions', 'analysis_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'analysis_json',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('missions', 'notes')
    op.drop_column('missions', 'duration')
    op.drop_column('missions', 'constraints')
    op.drop_column('missions', 'budget')
    op.drop_column('missions', 'equipment')
    op.drop_column('missions', 'vehicles')
    op.drop_column('missions', 'personnel')
    op.drop_column('missions', 'risk_tolerance')
    op.drop_column('missions', 'priority')
    op.drop_column('missions', 'environment')
    op.drop_column('missions', 'objective')
    # ### end Alembic commands ###
